name: 同步上游仓库代码 触发阿里云ACR自动构建
permissions:
  contents: write

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync_fork:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: ${{ secrets.UPSTREAM_REPO }}
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GH_PAT || github.token }}
          test_mode: false

      - name: 同步失败告警
        if: failure()
        run: |
          echo "[Error] 上游工作流文件变更，定时同步暂停，请手动同步一次Fork"
          exit 1
